### ISSUE TITLE
TuxBuilder crashes when adding a spawnpoint to a level

### ISSUE THREAD

**Issue by tobbi** [Alzter/TuxBuilder#27]
Steps to reproduce:
1. Start TuxBuilder
2. Go into edit mode by right-clicking
3. Go to Objects > Misc > Spawnpoint.
4. Click into the sector.

Results:
Tux Builder crashes.
```
			get_tree().current_scene.get_node(str("Level/", object_dragged)).position = $SelectedTile.position
``` 

Expected result:
Spawnpoint gets added to the game.

**Comment by Alzter** [comment]
Fixed
