### ISSUE TITLE
Edits always reverted when using HTML5 version

### ISSUE THREAD

**Issue by qwertychouskie** [Alzter/TuxBuilder#28]
https://jacobspctuneup.tk/TuxBuilder/HTML5/

Editing the level reverts the changes as soon as the editor is exited.

TuxBuilder built from https://github.com/Alzter/TuxBuilder/commit/13d29c0d7e837a72e09939a8ef654b1013bd22cc.

**Comment by Alzter** [comment]
Odd, this isn't a bug in my version. The current edited level is supposed to save into Levels/EditedLevel.tscn but maybe compiling Tux Builder messes with that.

**Comment by tobbi** [comment]
I think the problem is that the html5 page has no write access to the res:// path.

**Comment by Calinou** [comment]
> I think the problem is that the html5 page has no write access to the res:// path.

This is correct, `res://` isn't guaranteed to be writable to on all platforms. (If you install the game to a system-wide location on Windows or Linux, the same issue will occur.)

User data should be saved to `user://` instead. (On HTML5, this will use localStorage, as you can't manipulate the user's filesystem directly.)

**Comment by qwertychouskie** [comment]
Fixed on my HTML5 build: https://jacobspctuneup.tk/TuxBuilder/HTML5/

Modified `Gameplay.gd`: [Gameplay.gd.txt](https://github.com/Alzter/TuxBuilder/files/3699992/Gameplay.gd.txt)

Feel free to commit if you think it's good.

**Comment by qwertychouskie** [comment]
@Alzter / @tobbi Can one of you check if the above code is correct and commit it if it is?  Thanks

**Comment by skyace65** [comment]
The code seems good to me so I'm going to merge a PR with the changes.
