### ISSUE TITLE
Layer scroll and move speed boxes allow decimal inputs but appear as rounded inputs

### ISSUE THREAD

**Issue by Alzter** [Alzter/TuxBuilder#43]
When you try to put decimal inputs into the scroll or move speed boxes in the layer settings menu, the value is saved as round but the spinbox displays it as a rounded value.

![image](https://user-images.githubusercontent.com/22513909/64482825-56f0c080-d23c-11e9-9087-1c2ca3f390dd.png)

This may be an issue with Godot itself, so I'm not sure if it's possible to fix.

**Comment by tobbi** [comment]
Did you fix this @Alzter ?

**Comment by Alzter** [comment]
> Did you fix this @Alzter ?

no

**Comment by Alzter** [comment]
Fixed it
