### ISSUE TITLE
Sliding

### ISSUE THREAD

**Issue by Alzter** [Alzter/TuxBuilder#44]
Just sliding in general needs a lot of work to happen.

First we need sliding physics. I'd imagine them to act like Sonic's roll physics, you gain momentum by going downhill (which is increased by the steepness of the slope) and then can use that momentum to go up hills or ramps. It'd be cool to have Tux be able to slide up walls if he went up a ramp but it's not required.

Second we need slopes to exist. There should be multiple variations of smooth slopes to slide on and slopes should probably auto-tile. Maybe there should be a tool to place slopes?

**Comment by tobbi** [comment]
Sliding seems to be working in a rudimentary way. What's there still to do?

**Comment by Alzter** [comment]
I might shelve sliding for the time being to focus on getting everything else more polished. I'm not sure how placing slopes or ramps would work but I do know we don't need the sliding physics to be too complicated to work, just as long as you can do things like go down slopes and then fly off inclines.
