### ISSUE TITLE
Glitch with ramps and ceilings

### ISSUE THREAD

**Issue by Rami-Slicer** [Alzter/TuxBuilder#49]
If you place a ramp 2 blocks below a full tile as shown below, Tux will get stuck and the ceiling collision sound will play nonstop until you duck out of it. 
![Screenshot_20191017_101134](https://user-images.githubusercontent.com/40865625/67022386-c4f39780-f0c6-11e9-8147-2da021a3f667.png)

**Comment by Alzter** [comment]
The ceiling collision sound plays nonstop if Tux is stuck in any solid surface, since technically he is touching it with the top of his hitbox (at least that's how I think the ceiling detection works).
